name: abibotti
description: Backend YO-koe
version: 1.0.0

environment:
  sdk: '^3.7.0'

dependencies:
  dart_frog: ^1.2.0
  http: ^0.13.6
  postgres: ^2.4.2
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.5.1
  mime: ^1.0.4